const {chromium} = require('playwright');
const {mockGM} = require('./browser.cjs');
const fs=require('node:fs');
fs.mkdirSync('work', {recursive: true});
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.CHROME_EXECUTABLE || undefined,headless:true});
 const context=await browser.newContext({colorScheme:'dark'});
 await context.route('https://www.bilibili.com/isolation-test',r=>r.fulfill({contentType:'text/html',body:'<!doctype html><html><head><style>body{background:white;color:black}.card{background:white;color:black}</style></head><body><p class="card">隔离环境</p><div id="host"></div></body></html>'}));
 const page=await context.newPage();await page.goto('https://www.bilibili.com/isolation-test');
 const session=await context.newCDPSession(page);
 const {frameTree}=await session.send('Page.getFrameTree');
 const {executionContextId}=await session.send('Page.createIsolatedWorld',{frameId:frameTree.frame.id,worldName:'userscript-test'});
 const source=`(${mockGM.toString()})();\n${fs.readFileSync('bilibili-system-theme.user.js','utf8')}`;
 const res=await session.send('Runtime.evaluate',{expression:source,contextId:executionContextId});
 assert(!res.exceptionDetails,JSON.stringify(res.exceptionDetails));
 await page.waitForTimeout(400);
 assert.notEqual(await page.locator('.card').evaluate(n=>getComputedStyle(n).backgroundColor),'rgb(255, 255, 255)');
 await page.evaluate(()=>document.querySelector('#host').attachShadow({mode:'open'}).innerHTML='<style>p{color:black;background:white}</style><p>后加载评论</p>');
 await page.waitForTimeout(500);
 assert.notEqual(await page.locator('#host p').evaluate(n=>getComputedStyle(n).backgroundColor),'rgb(255, 255, 255)');
 await session.send('Runtime.evaluate',{expression:'GM_setValue("bili-system-theme.mode", "light")',contextId:executionContextId});
 await page.waitForTimeout(200);
 assert.equal(await page.locator('style.darkreader').count(),0);
 assert.equal(await page.locator('#host p').evaluate(n=>getComputedStyle(n).backgroundColor),'rgb(255, 255, 255)');
 await session.send('Runtime.evaluate',{expression:'GM_setValue("bili-system-theme.mode", "auto")',contextId:executionContextId});
 await page.waitForTimeout(200);
 assert.equal(await page.locator('html').getAttribute('data-bili-system-theme'),'dark');
 await page.emulateMedia({colorScheme:'light'});await page.waitForTimeout(200);
 assert.equal(await page.locator('style.darkreader').count(),0);
 console.log('PASS Chrome isolated execution world, initial dark, later shadow roots, GM setting callback, switch to light');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
